### PR TITLE
refactor(loading): simplify how singleton services are provided

### PR DESCRIPTION
**Pull request by jotatoledo**
## Description

Since v6 angular provides a new way of registering singleton services by means of the provide in root module pattern. The changes aim to make use of this feature.

#### Test Steps

- [ ] `npm run serve`
- [ ] then this
- [ ] finally this

#### General Tests for Every PR

- [ ] `npm run serve:prod` still works.
- [ ] `npm run tslint` passes.
- [ ] `npm run stylelint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build:lib` still works.

### CODE REVIEW

**Comment by jotatoledo** [comment]
@emoralesb05 error seems to be some random failure on travis

**Comment by emoralesb05** [comment]
This one i think we might have to provide it at the module level.. it doesnt work without the entryComponents.

**Comment by jotatoledo** [comment]
@emoralesb05 any hints on the errors that you are seeing? how can I reproduce them?

**Comment by jeremysmartt** [comment]
@jotatoledo Conflicts

**Comment by jeremysmartt** [comment]
This will become OBE with:
https://github.com/Teradata/covalent/issues/1401

**Comment by kriswinbush** [comment]
closing this will be covered in #1401

**Pull request closed without merging**
