### PR TITLE
fix(dataTableService): Sorting simplified and fixed for date type

### PR DESCRIPTION
**Pull request by pascalwhoop**
Let's just leave javascript to handle the sorting. If its a number, it will sort correctly, same goes for strings and dates/strings of dates.

related to issue #461

### CODE REVIEW

**Comment by emoralesb05** [comment]
The reason we had it that way is because there are times we want to sort numbers that are strings. 

Not everything will be in its correct type.

**Comment by pascalwhoop** [comment]
A number that is a string will still sort correctly though as "1" is still
smaller than "11" or "19" isn't it?

**Comment by emoralesb05** [comment]
In the case of "11" and "19" yes, but if you compare "100" with "20", turns out that "100" will be taken as lower than "20" because `string`s are compared character by character left to right.

This is true in all the languages (or at least the ones i know)

**Comment by pascalwhoop** [comment]
Okay, true. Mhm maybe an additional attempt of parsing the string as a date
before parsing it as a number would be a good approach? If you'd think that
is a better idea, I'll update the PR, adding a commit that does
1. check if date --> date compare
2. check if number --> number compare
3. assume string --> string compare

**Comment by emoralesb05** [comment]
Yep, that would be awesome! 😄

**Comment by pascalwhoop** [comment]
How would you think about including moment.js in the project? I have reservations about my proposed solution as it seems to be a more complex field than I originally anticipated
https://stackoverflow.com/questions/7445328/check-if-a-string-is-a-date-value

They argue that its not as intuitive as one would think (e.g. just checking if `Date.parse('somestring')` returns "Invalid Date" or not. So I think this needs to be done properly rather than me just giving it a quick fix. I could include moment in the build and use the library for that if you agree with adding this dependency.

**Comment by pascalwhoop** [comment]
The alternative (IMHO somewhat dirty) solution would be something in the lines of 

```
if(isNaN(compA) && isNaN(compB) && isValidDate(compA) && isValidDate(compB){
    // do date comparison
}else{
    // same code as before
}

**Comment by emoralesb05** [comment]
Well, the reason we abstracted the sorting function from the data-table was so people can implement their own. Be it server side or any other type of sorting algorithm + we didnt want to include `moment.js` as part of our library for the time being if possible. 

I agree that the issue is not simple to fix, so it might require a bit more brainstorming before continuing.

**Comment by RemcovandenBerg** [comment]
Workaround.. 
```
 this._dataTableService.sortData = 
      (data: any[], sortBy: string, sortOrder?: TdDataTableSortingOrder): any[] => {

        let looksLikeAnISODate = (compA: any): boolean => {
          if (!compA) return false;
          if (compA.length < 19) return false;
          return (compA[4] == '-') && (compA[7] == '-') && (compA[10] == 'T');
        }

        let determinedIsoSort = false;
        let isoSort = false;
        let getIsIsoDateColumnSortable = (compA, compB: any) : boolean =>{
            if (determinedIsoSort) return isoSort;
            isoSort = looksLikeAnISODate(compA) || looksLikeAnISODate(compB);
            determinedIsoSort = !!compA || !!compB;
            return isoSort;
        }        

        if (sortOrder === void 0) { sortOrder = TdDataTableSortingOrder.Ascending; }
        if (sortBy) {
            data = Array.from(data);
            data.sort(function (a, b) {
                var compA = a[sortBy];
                var compB = b[sortBy];
                
                var direction = 0;
                let sortAsNumber =  !Number.isNaN(Number.parseFloat(compA)) && !Number.isNaN(Number.parseFloat(compB));
                let isIsoDateColumn = getIsIsoDateColumnSortable(compA, compB);
                if (sortAsNumber && !isIsoDateColumn) {
                    direction = Number.parseFloat(compA) - Number.parseFloat(compB);
                }
                else {
                  if (!compA) compA = "";
                  if (!compB) compB = "";

                    if (compA < compB) {
                        direction = -1;
                    }
                    else if (compA > compB) {
                        direction = 1;
                    }
                }
                return direction * (sortOrder === TdDataTableSortingOrder.Descending ? -1 : 1);
            });
        }
        return data;
    };
```

**Pull request closed without merging**
