### PR TITLE
chore(): upgrade to material/cdk@beta.10

### PR DESCRIPTION
**Pull request by emoralesb05**
## Description
Making covalent support all the breaking changes (and deprecating changes) coming from material following their changelog https://github.com/angular/material2/blob/master/CHANGELOG.md#200-beta10-découpage-panjandrum-2017-08-29

### What's included?

- 68dcd00 fix(layout-docs): workaround for now since MdSidenav has issues when opening -
- sometimes at the beggining
- a851506 chore(dynamic-forms): update slider label using new classes
- afb48b6 chore(dynamic-forms): use flex row to stetch inputs/textareas
- 83b394b fix(paging): fix padding on md-selects used in td-paging-bar
- 70583f2 chore(paging): set fixed 30px in input since it has 200px by default in the paging demo
- df549f9 fix(data-table): fix color of pseudo checkboxes in data-table
- dce9a03 fix(chips): md-basic-chip behaves diff now so click on chip was not working
- 893d831 chore(): update platform package.json's with bumps
- e061084 chore(): bump to angular@4.3.X since its a requirement for angular/material now
- 67c6de9 chore(): rename md-list-icon and md-list-avatar to mdListIcon and mdListAvatar
- c4c6e74 chore(): rename md-ripple to mdRipple
- ce77bfd chore(): rename md-input-container to md-form-field and its classes
- 5780da4 chore(): rename md-card-avatar to mdCardAvatar
- e7d57a4 chore(): rename md-tab-label to mdTabLabel
- 9b96116 chore(): rename md-line with mdLine
- 3078ece fix(steps): fix demo to start in vertical mode
- 5ed8a3e feat(): rename mat-sidenav- classes to mat-drawer- and replace align input with position input
- 1a01edb fix(): fix breaking changes from cdk imports and interface modifications in material
- 804ba29 chore(): update rollup script with cdk dependencies
- ba65133 chore(): upgrade to material/cdk@beta.10

#### Test Steps

- [ ] `yarn install`
- [ ] `ng serve`
- [ ] Test everything!

#### General Tests for Every PR

- [ ] `ng serve --aot` still works.
- [ ] `npm run lint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build` still works.

### CODE REVIEW

**Comment by emoralesb05** [comment]
Opened PR just as a placeholder.. i only solved the compilation errors, but there are lots of small issues around layouts, chips, etc etc

**Comment by jotatoledo** [comment]
Is there any eta? 😄

**Comment by emoralesb05** [comment]
We are trying to target early next week since we also have some data-table features and virtual scroll `base` implementation :P so stay tuned!

**Comment by jerryorta-dev** [comment]
A visited link in a dark theme is extremely difficult to read. IMO.

screen shot 2017-08-31 at 12 38 25 pm

**Comment by jerryorta-dev** [comment]
Chip Events:
http://localhost:4200/#/components/chips

`ERROR Error: ExpressionChangedAfterItHasBeenCheckedError`

chip-event-error

**Comment by jerryorta-dev** [comment]
Loading Style/layout
http://localhost:4200/#/components/loading

Input label crashes into tab header underline.
loading-input-label-crash

**Comment by kyleledbetter** [comment]
@jerryorta-dev i think that already happens https://teradata.github.io/covalent/#/components/loading

**Comment by jerryorta-dev** [comment]
Data Table with components
http://localhost:4200/#/components/data-table

`ExpressionChangedAfterItHasBeenCheckedError: ` when changing number or rows displayed.

data-table-error

**Comment by emoralesb05** [comment]
I think the chips was introduced before, but great catch. Pushed a commit to fix it

**Comment by jerryorta-dev** [comment]
Dynamic File Input Element
http://localhost:4200/#/components/dynamic-forms

Text overlays default text after selecting a file to upload.
Change events are not detected.

**Comment by emoralesb05** [comment]
That seems to me like an `mdInput` issue, so we should probably open an issue to track this. Thanks @jerryorta-dev

**Comment by emoralesb05** [comment]
@jotatoledo we are gonna release after we merge this and after i merge another PR with data table features and virtual scroll implementation (basic)

**Comment by akrepon** [comment]
The paging module seems to effect the md-select. I see that several things are removed from the TdPagingComponent such as the pageSizes, etc... Since these are no longer used I think the css for this component should be removed  as well.

**Comment by tuanngominh** [comment]
After switching to nightly build and material.beta.10, cdk.beta.10
```
"@angular/cdk": "^2.0.0-beta.10",
"@angular/material": "^2.0.0-beta.10",
"@covalent/core": "git+https://github.com/Teradata/covalent-nightly.git",
```

The paginator still works before upgrade but now there is error message
```
Template parse errors:
Can't bind to 'pageSizes' since it isn't a known property of 'td-paging-bar'
```
My paging code
```
<td-paging-bar #pagingBar [pageSizes]="[defaultPagesize, 20, 25]" [total]="totalRows" (change)="onPage($event)">
  <span td-paging-bar-label hide-xs>Row per page:</span>
  {{pagingBar.range}} <span hide-xs>of {{pagingBar.total}}</span>
</td-paging-bar>
```
Remove the `[pageSizes]="[defaultPagesize, 20, 25]"`, then paginator works again.

**Comment by emoralesb05** [comment]
@tuanngominh if you are using the nightly build, you need to be aware that there might be breaking changes like that one.

**Pull request merged**
