### PR TITLE
feat(dependencies): upgrade covalent dependencies @angular@5.1

### PR DESCRIPTION
**Pull request by emoralesb05**
## Description
Now that material introduced their `MatDividerModule`, we can directly use it without using `MatListModule`.. To be able to use this we need to upgrade material to 5.1

So to keep consistency we are gonna have a minimal requirement of angular@5.1

#### Test Steps

- [x] `npm run serve`
- [x] See everything working fine

#### General Tests for Every PR

- [ ] `npm run serve:prod` still works.
- [ ] `npm run tslint` passes.
- [ ] `npm run stylelint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build:release` still works.

### CODE REVIEW

**Comment by stevenov7** [comment]
http://localhost:4200/#/components/json-formatter
looks like divider is going right though the middle of the "Original JSON Object:" text.
screen shot 2018-01-18 at 5 56 42 pm

**Comment by stevenov7** [comment]
http://localhost:4200/#/components/dynamic-forms
looks like divider below "Select a type, add element then update" is not staying in its box 
screen shot 2018-01-18 at 6 02 58 pm

**Comment by stevenov7** [comment]
http://localhost:4200/#/components/code-editor
Hmm dead image link from cdn.rawgit.com we are using for covalent+electron image
https://cdn.rawgit.com/Teradata/covalent-electron/develop/src/app/assets/icons/covalent-and-electron.svg

screen shot 2018-01-18 at 6 06 08 pm

**Comment by emoralesb05** [comment]
The last find is in the `code-editor` repo, not in this one.. so we have to fix it there @stevenov7

**Pull request merged**
