### PR TITLE
feat(): upgrade to angular@4.0.0. (closes #393)

### LINKED ISSUE #393: [Feature] Upgrade to @angular@4.0.0 when stable.
#### Feature Request

We are going to have to make a though call when `4.0.0` is stable because its going to be hard to support `2.X` and `4.X` in the same release.

Either we branch off and support both versions for 1-2 releases (which will be a pain), or just go full on steam ahead with `4.0.0` since we are trying to be cutting edge.. which i am more inclined to do so since `4.0.0` has significant performance enhancements and code reduction.

Note: since we heavily depend on `material` we should see how the handle it too.

### PR DESCRIPTION
**Pull request by emoralesb05**
## Description

https://github.com/Teradata/covalent/issues/393
Starting the PR (will set its description later)

### What's included?

- chore(): upgrade to angular@4.0.0 (and dependencies)
- feat(): replace `template` with `ng-template`
- feat(): replace `OpaqueToken` with `InjectionToken`
- feat(): import `BrowserAnimationsModule` where needed
- chore(flex-layout): update to rc.1 for ng@4.0.0 support
- feat(): remove Renderer infavor of Renderer2
- feat(toggle): support for ng4
- feat(fade): support for ng4

#### Test Steps

- [ ] do this
- [ ] then this
- [ ] finally this

#### General Tests for Every PR

- [ ] `ng serve --aot` still works.
- [ ] `npm run lint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build` still works.

##### Screenshots or link to CodePen/Plunker/JSfiddle

### CODE REVIEW

**Comment by d3viant0ne** [comment]
On the off chance you missed this as opposed to just haven't gotten to it yet..

`src/platform/core/common/animations` `fade && toggle` are still using `renderer.setElementStyle`

**Comment by emoralesb05** [comment]
Yes, i was waiting on this to see if we can still use `Renderer` for now or access directly `@angular/animations/browser` pre `4.1.0-beta` as stated in https://github.com/angular/angular/issues/15294#issuecomment-287848550. If `Renderer` will still be there until `4.1.0`, then we can just keep using it for now.

**Comment by mmoravcik** [comment]
Any idea when is this going to be released? Great framework BTW

**Comment by d3viant0ne** [comment]
@mmoravcik - It's available in the nightly

**Comment by mmoravcik** [comment]
@d3viant0ne thanks but still getting the following when running `ng build prod` with CLI



    ERROR in _gendir/node_modules/@covalent/core/data-table/data-table.component.ngfactory.ts     (1,1): Property '_selectable' is private and only accessible within class 'TdDataTableComponent'.

    /node_modules/@covalent/core/data-table/data-table.component.html (14,5): Property '_data' is private and only accessible within class 'TdDataTableComponent'.

    $$_gendir/node_modules/@covalent/core/data-table/data-table.component.ngfactory.ts (1,1): Property '_selectable' is private and only accessible within class 'TdDataTableComponent'.

**Comment by d3viant0ne** [comment]
Already reported in #471 which has an open pull request.

**Pull request merged**
