### PR TITLE
fix(rtl-demo): fix rtl/lrt demo in docs

### PR DESCRIPTION
**Pull request by emoralesb05**
there were issues when navigation between views or when using the td-layout.. state was lost and sidenavs were not working as intended.

#### Test Steps

- [ ] `ng serve`
- [ ] Go to docs and go to `rtl` mode

#### General Tests for Every PR

- [ ] `ng serve --aot` still works.
- [ ] `npm run lint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build` still works.

##### Screenshots or link to CodePen/Plunker/JSfiddle

### CODE REVIEW

**Comment by jerryorta-dev** [comment]
Refreshing the browser while in `rtl` mode throws this error:

```javascript

ERROR TypeError: Cannot read property 'toArray' of undefined
    at MdSidenavContainer._validateDrawers (material.es5.js:11389)
    at material.es5.js:11287
    at SafeSubscriber.schedulerFn [as _next] (core.es5.js:3842)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.next (Subscriber.js:185)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at EventEmitter.Subject.next (Subject.js:55)
    at EventEmitter.emit (core.es5.js:3816)
    at Dir.set [as dir] (material.es5.js:341)

```

**Comment by jerryorta-dev** [comment]
This scenario takes a very long time ( 3s ) to transition views - I thought it was a dead link at first:

1. Load the browser in the Home View: `http://localhost:4200/#/`
2. Select `RTL` mode.
3. Navigate to `templates` - `http://localhost:4200/#/templates`

**Comment by jerryorta-dev** [comment]
Unit tests pass, but there is **a lot** of console log output. 

```bash

ERROR: 'ERROR', TypeError{ngDebugContext: DebugContext_ ...

```

**Comment by emoralesb05** [comment]
The 3 seconds thing happens with lazy module loading + JIT, it doesnt really happen in production (AoT).

That being said, found a weird behavior where since `/templates` is the last route, when trying to access it it loads all the chunks when it shouldnt, so good find.

**Comment by emoralesb05** [comment]
Fixed issue with `rtl` refresh since its the `material` sidenav was trying to check its children before it has any. Had to do the change to `rtl` once everything is safely injected

**Comment by jerryorta-dev** [comment]
I realized the lazyload issue once I saw the routes.

The site [https://teradata.github.io/covalent](https://teradata.github.io/covalent) is production, correct?  It's still a little slow on route changes there too.

I have a selective-preload-strategy I can implement if you want to give it a go. It lazy loads immediately, after the first module loads.

**Comment by jerryorta-dev** [comment]
Since lazyload is not a part of this issue, this is approved.

**Comment by emoralesb05** [comment]
We can discuss that approach offline. 👍

**Pull request merged**
