### PR TITLE
feat(td-search): expose appearance property

### LINKED ISSUE #1374: [Feature] Search-box and Search-Input appearance exposure.
#### Feature Request

Expose appearance input from `mat-form-field`.

### PR DESCRIPTION
**Pull request by jotatoledo**
## Description

* Add a new input property to the search input component
in order to expose the appearance of the wrapped
mat-form-field element
* Add a new input property to the search box component
in order to expose the appearance of the wrapped
td-search-input component

Closes #1374 

### What's included?

- API modifications
- Doc changes

#### Test Steps

- [x] `npm run serve`
- [ ] then this
- [ ] finally this

#### General Tests for Every PR

- [ ] `npm run serve:prod` still works.
- [ ] `npm run tslint` passes.
- [ ] `npm run stylelint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build:lib` still works.

### CODE REVIEW

**Comment by emoralesb05** [comment]
Awesome man! thanks for this.

**Comment by jotatoledo** [comment]
Ill amend the last commit with an update for the demo and then the pr would be ready for review

**Comment by jotatoledo** [comment]
@emoralesb05 ready for review

Most likely some style changes are required

**Comment by emoralesb05** [comment]
Sorry for the late review dude. Thanks for the PR!

**Pull request merged**
