### PR TITLE
feat(IE11): Platform & Docs support for IE11

### PR DESCRIPTION
**Pull request by kyleledbetter**
## Description

Following the Flexbox quirks & lack of full support [documented here](https://github.com/philipwalton/flexbugs), this PR has small fixes & workarounds for several components and documentation app areas, as well as IE11 docs for necessary polyfills and workarounds.

### What's included?

- IE11 Docs site fixes
- IE11 support documentation
- IE11 fixes for Logo md-icon sizing
- IE11 fixes for Chips component
- IE11 fixes for Navigation Drawer component
- IE11 fixes for Message component
- IE11 fixes for Notification count component in toolbar
- IE11 fixes for Layout docs demos (height)
- IE11 style for layout scss
- overflow-visible utility style
- IE11 polyfills for NGX-Charts

#### IE11 VM for OSX/macOS

- [x] Download & install Virtualbox http://download.virtualbox.org/virtualbox/5.1.26/VirtualBox-5.1.26-117224-OSX.dmg
- [x] Download IE11 on Win81 for Virtualbox from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
- [x] `tar xf IE11.Win8.1.For.Windows.VirtualBox.zip`
- [x] Open Virtualbox and import IE11 - Win8.1.ova
- [x] Run IE11
- [x]  you may need to turn on Internet Sharing in macOS Settings > Sharing

#### Test Steps

- [x] check out `feature/ie11`
- [x] `rm -rf node_modules`
- [x] `yarn install`
- [x] `ng serve --host 0.0.0.0 --disable-host-check`
- [x]  in IE11 VM visit `http://10.0.2.2:4200`

#### Test Covalent

- [x] Test Docs homepage and make sure sections are overflowing
- [x] Test Chips and see that they have proper width
- [x] Test Message and see that they're properly vertically center
- [x] Test Notifications and see that the notification icon in the toolbar isn't chopped off
- [x] Test Navigation drawer and see that it has the proper height (may need browser resize for change detection)
- [x] Test Layout docs and see they have proper height for demos
- [x] Test NGX Charts to see that it actually loads (there are card chart issues beyond our fix)
- [x] Read /docs/IE11.md

#### General Tests for Every PR

- [x] `ng serve --aot` still works.
- [x] `npm run lint` passes.
- [x] `npm test` passes and code coverage is not lower.
- [x] `npm run build` still works.

##### Screenshots or link to CodePen/Plunker/JSfiddle
image

image

image

image

image

image

image

image

### CODE REVIEW

**Comment by emoralesb05** [comment]
Added a few things:

- [x] chore(): update yarn.lock with latest dependencies
- [x] fix(chips): fix autocomplete click selection for chips
- [x] chore(build): add autoprefixer to build process to ensure all css is prefixed for every browser.

The last one will make sure we dont have CSS issues across browsers (for the most part)

e.g.

SCSS

```css
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    align-items: flex-start;
```


Compiled CSS before autoprefixer: 

```css
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    align-items: flex-start;
```

Compiler CSS after autoprefixer:

```css
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: horizontal;
    -webkit-box-direction: normal;
        -ms-flex-direction: row;
            flex-direction: row;
    -ms-flex-wrap: wrap;
        flex-wrap: wrap;
    -webkit-box-align: start;
        -ms-flex-align: start;
            align-items: flex-start;
```

**Comment by kyleledbetter** [comment]
nice! thx @emoralesb05!

**Comment by stevenov7** [comment]
- [ ] Test Docs homepage and make sure sections are overflowing
Case 1: Chrome (Left) / IE11 (Right) notice overflow break not as clean as Chrome
rec2
Case 2: Chrome (Left) / IE11 (Right) notice overflow break not as clean as Chrome
rec5

**Comment by jerryorta-dev** [comment]
- [ ] IE not rendering Example Charts blocks correctly ( also seen in screenshots in main PR ).

example-charts-chrome
example-charts-ie

**Comment by stevenov7** [comment]
- [ ] Test Chips and see that they have proper width
Case 1: Chrome (Left) / IE11 (Right) Alignment of chips + chips "Enter auto..." input + remove "X" is not centered
screen shot 2017-08-28 at 10 57 59 am

**Comment by emoralesb05** [comment]
Pushed a fix for the chips alignment issue https://github.com/Teradata/covalent/pull/831/commits/025e79b3371e973abf2108aaeeb50ad36822828a

**Comment by aciccarello** [comment]
Form in expantion panel documentation is overlapping in IE.
http://localhost:4200/#/components/expansion-panel

image

**Comment by aciccarello** [comment]
Prompt dialog buttons are being pushed up into the input.
http://localhost:4200/#/components/dialogs

In IE:
image

In Chrome:
image

**Comment by jeremysmartt** [comment]
Strange, clicking in the jump to box causes everything to go away

paging wierd

**Comment by jeremysmartt** [comment]
Dynamic Forms looks off:

screen shot 2017-08-28 at 12 15 44 pm

**Comment by jeremysmartt** [comment]
Select Boxes look off in IE:

screen shot 2017-08-28 at 12 18 02 pm

**Comment by jeremysmartt** [comment]
SVG from <td-readme-loader> looks off:

screen shot 2017-08-28 at 12 18 57 pm

**Comment by aciccarello** [comment]
## Data Table
- Sort icon is mis-aligned and jumps around

ie11 data table sort icon alignment

- Error and persistant title on row selection

image

Chrome for comparison:
image


- Icons in data table demo overlap text

image

**Comment by kyleledbetter** [comment]
fix for the prompt dialog pushed 
https://github.com/Teradata/covalent/pull/831/commits/dd761493f5670ef92c9a75e5b9b32191aa314c1c

ref: https://github.com/Teradata/covalent/pull/831#issuecomment-325445793
thx @aciccarello

**Comment by emoralesb05** [comment]
fix loading demo issue in IE11 https://github.com/Teradata/covalent/pull/831/commits/a37e79cc9c8764c57656af0ce5b75c5883dcb2af

**Comment by kyleledbetter** [comment]
fixed expansion panel form height issue with https://github.com/Teradata/covalent/pull/831/commits/2c414919903b9b5bed36d9222acc607d688c5718

ref https://github.com/Teradata/covalent/pull/831#issuecomment-325437102

**Comment by kyleledbetter** [comment]
fixed dynamic form overlap with https://github.com/Teradata/covalent/pull/831/commits/e9ac1b6d2ef7200f435268f2c8b350f2cc9e0e8e

ref: https://github.com/Teradata/covalent/pull/831#issuecomment-325451300
thx @jeremysmartt

**Comment by kyleledbetter** [comment]
fixed the data-table sorting arrow jumping around in IE11 https://github.com/Teradata/covalent/pull/831/commits/b4a06c80bc864369eb93c7eb32fc3ed72f0424fe

**Comment by emoralesb05** [comment]
fixed an additional issue with md-select paging width in ie11 https://github.com/Teradata/covalent/pull/831/commits/d088a87346820d92573c5e2ac30e35102054978e

**Comment by emoralesb05** [comment]
I think this is a good enough base for now. If there are any other IE11 (which they are) we should open specific issues in the repo so we can tackle them separately. 

Gonna merge this one for now.

**Comment by aciccarello** [comment]
:clap: Thanks for this work. IE11 support is still a requirement for TD ITS projects so this is very helpful.

**Pull request merged**
