### PR TITLE
feature(theming): create covalent-theme for components

### PR DESCRIPTION
**Pull request by kyleledbetter**
## Description

Create covalent-theme following material2 guildelines https://github.com/angular/material2/blob/master/docs/theming-your-components.md

### What's included?

- covalent-theme
- paging-bar theme
- next component theme

#### Test Steps

- [x] ng serve
- [x] view all covalent components to verify themes working
- [x] test different primary/warn/accent colors in /src/theme.scss
- [x] test light and dark theme by changing /src/theme.scss `$theme: md-light-theme($primary, $accent, $warn);` to `$theme: md-dark-theme($primary, $accent, $warn);`
- [x] ng test

##### Screenshots or link to CodePen/Plunker/JSfiddle

Paging bar:
image

### CODE REVIEW

**Comment by kyleledbetter** [comment]
Adding  file upload (the only theme is the cancel circle bg color):

light:
image


dark:
image

**Comment by kyleledbetter** [comment]
Adding stepper theme:
light:
image


dark:
image

**Comment by kyleledbetter** [comment]
Adding expansions:
light
image

dark
image

**Comment by kyleledbetter** [comment]
Adding chips:
light:
image

dark:
image

**Comment by kyleledbetter** [comment]
Add loading

light
image

dark
image

**Comment by kyleledbetter** [comment]
Update json-formatter using custom primary/accent/warn

light
image

dark
image

**Comment by kyleledbetter** [comment]
Added markdown theme:
light
image

dark
image

**Comment by kyleledbetter** [comment]
Add charts theme:
light
image

dark
image

**Comment by kyleledbetter** [comment]
Add layout theming
everything!
dark-theming

**Comment by indyplanets** [comment]
👍 Tested and LGTM!

**Comment by emoralesb05** [comment]
Just added a restriction in layouts. LGTM!

**Pull request merged**
