### PR TITLE
feat(message): add animation when opening/closing

### PR DESCRIPTION
**Pull request by emoralesb05**
## Description

Message component works great, but now its time to make it sexier!

Adding a mix of collapse/fade animation when opening/closing the message component to give it a better look and feel.

### What's included?

- No API changes, internal animation added when opening/closing the component leveraging `tdCollapse` and `tdFadeInOut` animations.

#### Test Steps

- [x] Go to http://localhost:4200/#/components/message
- [x] Play with visibility demo

#### General Tests for Every PR

- [x] `ng serve --aot` still works.
- [x] `npm run lint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [x] `npm run build` still works.

##### Screenshots or link to CodePen/Plunker/JSfiddle

### CODE REVIEW

**Comment by bengwall** [comment]
Just an FYI...  should fateAnimation() be fadeAnimation()?

**Comment by emoralesb05** [comment]
whoops haha good catch!

**Comment by emoralesb05** [comment]
Unit tests will fail until we merge https://github.com/Teradata/covalent/pull/608

**Comment by jerryorta-dev** [comment]
approved

**Comment by ilsiepotamus** [comment]
👍

**Pull request merged**
