### PR TITLE
Feature(RTL): add RTL support to all modules

### PR DESCRIPTION
**Pull request by akhedrane**
## Description

Add RTL support as explained in #323  

### What's included?
- add fab button to toggle between RTL/LTR mode
- add/check rtl support to following components:
   - [x] Chips
   - [x] Data Table
   - [x] Dialogs
   - [x] Expansion Panel
   - [x] File
   - [ ] Json Formatter
   - [x] Layout
   - [x] Menu
   - [x] Notifications
   - [ ] Paging
   - [x] Search
   - [x] Steps
   - [x] Dynamic Forms
   - [x] Highlight
   - [ ] Markdown

#### General Tests for Every PR
- [x] `ng serve --aot` still works.
- [x] `npm run lint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [x] `npm run build` still works.

##### Demo link 
[https://rakmana.github.io/covalent/](https://rakmana.github.io/covalent/)

### CODE REVIEW

**Comment by kyleledbetter** [comment]
Thanks @akhedrane! Will take a closer look soon, but really appreciate the contribution!

**Comment by akhedrane** [comment]
@kyleledbetter you're welcome. Big thanks to you for this great work.
I'am newbie in angular world but the most change are in the styles.

**Comment by emoralesb05** [comment]
This happened to me in another PR, not sure why the `code-coverage` got lower.. i need to check that out.

**Comment by emoralesb05** [comment]
Awesome, thanks for the contribution! Will create an additional PR to add a few modifications.

**Pull request merged**
