### PR TITLE
feat(upgrade): upgrade to us angular 7 rc.0/1

### LINKED ISSUE #1241: Angular 7 release
Hi, 

are you planning on releasing stable version for Angular 7 when its available (in few weeks)? I noticed you skipped Angular 6 and there seems to be little to no updates which I find unfortunately since I happen to like this lib and use many of the components.

### LINKED ISSUE #1242: Wrong number of argument for theme in Angular material 7.0.0-beta.2
#### Bug Report

After upgrading to Angular material `7.0.0-beta.2` we encounter following exception when building the app:

```
ERROR in ./trainer/assets/material/material-theme.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./trainer/assets/material/material-theme.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
          ^
      Wrong number of arguments (3 for 1) for `mat-elevation'
      in c:\dev\FitRockApp\node_modules\@angular\material\_theming.scss (line 447, column 12)
ERROR in ./trainer/assets/theme/main.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./trainer/assets/theme/main.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
          ^
      Wrong number of arguments (3 for 1) for `mat-elevation'
      in c:\dev\FitRockApp\node_modules\@angular\material\_theming.scss (line 447, column 12)
```

This is caused by only importing covalent theme in our theming sass file:

`@import '~@covalent/core/theming/all-theme';`

This is likely related to the fact that mat-elevation has been removed from the stylesheet as mentioned in [release notes for 7.0.0-beta.2](https://github.com/angular/material2/releases/tag/7.0.0-beta.2)

### PR DESCRIPTION
**Pull request by stevenov7**
## Description
Upgraded Covalent to use Angular rc.0 and Angular Material rc.1
closes #1242 
closes #1241 

### What's included?

- Upgraded Covalent to use Angular rc.0 and Angular Material rc.1
- Fixed Safari fade in/out and collapse animation
- Removed some CovalentTests functions not being used and breaking typescript linting.

#### Test Steps

- [ ] `yarn install`
- [ ] `yarn serve`
- [ ] test (everything) as much as you can (demos/docs/ect) 

#### General Tests for Every PR

- [ ] `npm run serve:prod` still works.
- [ ] `npm run tslint` passes.
- [ ] `npm run stylelint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build:lib` still works.

### CODE REVIEW

**Comment by kyleledbetter** [comment]
Weird thing, when you scroll all the way down on the homepage there's a big space from this PR. Seems like it's perhaps bc of `cdkscrollable` or changes to the mat-drawer maybe?

Before:
image

After:
image

**Comment by kyleledbetter** [comment]
Seems like nav-list got a 1px space or something now:

Before:
image

After:
image

**Comment by kyleledbetter** [comment]
Ah the line is bc
```
.mat-drawer-side {

    border-right: solid 1px rgba(0, 0, 0, 0.12);

}
```

**Comment by emoralesb05** [comment]
- [x] Pushed a fix for the `border` in the sidenav

Cant seem to replicate the main page issue with the bottom space

**Comment by emoralesb05** [comment]
unit tests are hyper broken, so im gonna fix them.. i think its because of the animation changes.. so i could roll back that and we can fix it on a separate PR so we can focus more. Gonna investigate more.

**Comment by JulieMarie** [comment]
Think you got white on white here:
screen shot 2018-10-24 at 3 29 26 pm

**Comment by JulieMarie** [comment]
Broken image:
screen shot 2018-10-24 at 3 33 13 pm

**Comment by JulieMarie** [comment]
Scrollbar is funky (muahahahahaha):
screen shot 2018-10-24 at 3 39 04 pm

**Comment by JulieMarie** [comment]
Loader at top of page is barely visible:
loader

**Comment by JulieMarie** [comment]
Is this theme stuff right?
screen shot 2018-10-24 at 3 50 16 pm

**Comment by JulieMarie** [comment]
Should the link to Covalent Quickstart at the bottom be a button and open a new window?
screen shot 2018-10-24 at 3 52 46 pm

**Comment by JulieMarie** [comment]
Where is the link to Navigation Drawer at the bottom supposed to go to?
screen shot 2018-10-24 at 3 57 19 pm

**Comment by JulieMarie** [comment]
This is just a question, but are these templates still valid?
screen shot 2018-10-24 at 3 59 59 pm

**Pull request merged**
