### PR TITLE
feature(notifications): initial notifications module. (closes #148)

### LINKED ISSUE #148: Toolbar Notification Component
#### Feature Request

I'm seeing a trend that many of our apps with need a notification count/icon menu item w/ a dropdown menu w/ list items, etc

##### Screenshots or link to CodePen/Plunker/JSfiddle

image

### PR DESCRIPTION
**Pull request by emoralesb05**
## Description

Introducing new core submodule `notifications` module. (`CovalentNotificationsModule`) https://github.com/Teradata/covalent/issues/148

Adding core submodule `menu` for internal usage.

### `<td-notification-count>`

Use <td-notification-count> element to show number of notifications.

Properties:
image

#### Usage

```
  <td-notification-count color="primary | accent | warn" [notifications]="boolean | number">
     ... // could be an icon <md-icon>notifications</md-icon> or empty
  </td-notification-count>
```

#### Test Steps

- [x] `ng serve`
- [x] Go to http://localhost:4200/#/components/notifications
- [x] See docs and demo.
- [x] `npm run test`
- [x] `npm run tslint`
- [x] `npm run build`

##### Screenshots or link to CodePen/Plunker/JSfiddle

image

image

### CODE REVIEW

**Comment by kyleledbetter** [comment]
pushed updates
notifications

**Comment by emoralesb05** [comment]
- [x] Created inner `td-menu` (composition vs inheritance) for better layout inside `md-menu`

image

**Comment by emoralesb05** [comment]
- [x] scss fix for `notification-count`
- [x] Added more usage cases for `notification-count`

image

**Comment by emoralesb05** [comment]
- [x] Added `noCount` attribute to show a smaller notification

<td-notification-count color="accent" noCount [notifications]="true">

image

**Comment by richavyas** [comment]
observed an issue with search box placeholder `Search`:
scenario:
- click on search, write some text, close it, click on search sign again and check the search placeholder placement.

screen shot 2016-12-29 at 11 50 18 am

**Comment by emoralesb05** [comment]
Its actually always there, we just hide it when we focus the input.

**Comment by richavyas** [comment]
I pointed out the placement, not visible/hide. First time when search is clicked, it's placed correctly inside the input box. During second time, the text is shifted upwards.

**Comment by emoralesb05** [comment]
Cool, could you please open an issue to keep track of it?

**Pull request merged**
