### PR TITLE
chore(): upgrade to angular@5.1, material@5 and cli@1.6

### PR DESCRIPTION
**Pull request by emoralesb05**
## Description
Now that material is stable, we will update covalent to use the latest angular, material and cli.

#### Test Steps

- [x] `npm run reinstall`
- [x] See everything still working

#### General Tests for Every PR

- [x] `ng serve --aot` still works.
- [x] `npm run lint` passes.
- [x] `npm test` passes and code coverage is not lower.
- [x] `npm run build` still works.

### CODE REVIEW

**Comment by aciccarello** [comment]
Do you want to update TypeScript too?

**Comment by emoralesb05** [comment]
I tried doing it, but the `compiler-cli` complained that it doesnt support 2.5.. :/

**Comment by d3viant0ne** [comment]
@emoralesb05 - fwiw, i've been running on `typescript@2.6.2` on `angular@5.0.5` & the material rc for quite a while without adverse effect.

**Comment by kyleledbetter** [comment]
Looks like the change in Angular animations is disabling the child animation on the Demo 2:

Previously working (correct)
correct

In this branch (incorrect)
notworking

**Comment by kyleledbetter** [comment]
Found another child animation issue w/ sidenavs in layouts:

layout-animation

**Comment by kyleledbetter** [comment]
Updated the components to use a grid list
image

**Pull request merged**
