### PR TITLE
angular-cli latest deployed with rc.7

### PR DESCRIPTION
**Pull request by richavyas**
## Description

Updated current build to run app with angular-cli@latest, `1.0.0-beta.15` and webpack, `2.1.0-beta.22`

### What's included?

- angular-cli will use latest webpack Beta 22 now. 
- no use of moduleId anymore

#### Test Steps

- npm uninstall -g angular-cli
- npm cache clean
- rm -rf node_modules dist tmp
- npm install -g angular-cli@latest
- ng build
- ng serve

#### Issues with current buid

- Shadow DOM is not working with latest angular-cli. `/deep/` is deprecated and not working anymore.
- Issues with shadow dom on nested components mentioned here: https://github.com/angular/angular/issues/7400

##### Screenshots or link to CodePen/Plunker/JSfiddle

screen shot 2016-09-19 at 7 15 02 pm

### CODE REVIEW

**Comment by richavyas** [comment]
- [X] webpack build with `angular-cli@1.0.0-beta.15`
- [X] updated to use angular 2.0.0 & router 3.0
- [ ] hljs needs to be loaded correctly

webpack-15

**Comment by emoralesb05** [comment]
- [ ] Updated e2e setup.
- [ ] Updated karma setup.
- [ ] Updated travis CI config and added chrome support for travis.
- [ ] Added workaround for issue https://github.com/angular/angular-cli/issues/1930

**Comment by emoralesb05** [comment]
- [x] Had to use require for `highlight.js` since they dont have ES6/typescript support and avoided linting that line for that file only (so we dont use require anywhere else).

**Comment by indyplanets** [comment]
Getting these warnings when running `ng test`
```
29 09 2016 14:23:33.402:WARN [karma]: No captured browser, open http://localhost:9876/

WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
45:15 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
57:15 Critical dependency: the request of a dependency is an expression
```
Everything else looks good for running tests.

**Comment by indyplanets** [comment]
I'm getting an error in terminal when running `ng generate component my-new-component`. Component scaffolding seems to have been created properly. 😄 

```
installing component
  create src/app/my-new-component/my-new-component.component.scss
  create src/app/my-new-component/my-new-component.component.html
  create src/app/my-new-component/my-new-component.component.spec.ts
  create src/app/my-new-component/my-new-component.component.ts
Cannot read property 'read' of undefined
TypeError: Cannot read property 'read' of undefined
    at InsertChange.apply (/Users/jw186078/Projects/covalent/node_modules/@angular-cli/ast-tools/src/change.js:96:20)
    at /Users/jw186078/Projects/covalent/node_modules/@angular-cli/ast-tools/src/change.js:71:61
    at tryCatch (/Users/jw186078/Projects/covalent/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:195:12)
    at invokeCallback (/Users/jw186078/Projects/covalent/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:210:13)
    at /Users/jw186078/Projects/covalent/node_modules/es6-promise/dist/lib/es6-promise/then.js:24:16
    at flush (/Users/jw186078/Projects/covalent/node_modules/es6-promise/dist/lib/es6-promise/asap.js:94:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by emoralesb05** [comment]
@indyplanets that issue is known https://github.com/angular/angular/issues/11580, but since angular-cli doesnt allow custom `webpack.config.js` atm, we cant fix it until a next `angular-cli` version.

**Pull request merged**
