### PR TITLE
chore(): upgrade @ngx-translate to 6.0.0-beta.1

### PR DESCRIPTION
**Pull request by emoralesb05**
## Description

Upgrade `ng2-translate` to `@ngx-translate/core` and also include `@ngx-translate/http-loader`
https://github.com/ngx-translate/http-loader#ngx-translatehttp-loader--

#### Test Steps

- [x] `npm run reinstall`
- [x] See new resources card in `ngx-translate` docs.

#### General Tests for Every PR

- [x] `ng serve --aot` still works.
- [x] `npm run lint` passes.
- [x] `npm test` passes and code coverage is not lower.
- [x] `npm run build` still works.

### CODE REVIEW

**Comment by kyleledbetter** [comment]
Pushed a couple tweaks adding the translate buttons on each card w/ diff color:

image
image

**Comment by lincze** [comment]
does that mean that e.g. in date pipe '6 months ago"-like messages can also be translated?

**Comment by emoralesb05** [comment]
That one is a different issue that we are gonna tackle, but soon it will follow the `LOCALE_ID` like any other pipe.

We have this issue open to track that. https://github.com/Teradata/covalent/issues/324

**Comment by lincze** [comment]
thanks, I would have to find it

**Pull request merged**
