### PR TITLE
Add sortOrder property to ITdDataTableColumn interface

### PR DESCRIPTION
**Pull request by samaxes**
Useful when using [Data Table (Atomic) Components](https://teradata.github.io/covalent/#/components/data-table).

### CODE REVIEW

**Comment by emoralesb05** [comment]
You can just extend it and create your own custom one.

The problem with adding this is that in the normal case of the `data-table` component, it does have real use and it can be misleading as having it.

Having said this, we will probably need this soon when we make the data-table multi-sort compatible.

**Comment by samaxes** [comment]
@emoralesb05 yep, that's what I'm doing while it's not supported directly by data-table.

Is there any issue I can follow about the data-table multi-sort implementation status? And are there any docs available so I can have a look of how it works?

**Comment by emoralesb05** [comment]
Not yet, but we will add the issue soon since we need to develop it for our internal products too.

**Comment by samaxes** [comment]
Thanks.

**Comment by emoralesb05** [comment]
Closing this since we are in the design process on how to do multi sort.

**Pull request closed without merging**
