### PR TITLE
Added auto trim directive for string values

### PR DESCRIPTION
**Pull request by emoralesb05**
## Description

`TdAutoTrim` to trim string values on `blur` event. `ngModel` is required since it hooks into it.

#### Test Steps

- [x] use anywhere in code `<md-input tdAutoTrim [(ngModel)]="val"></md-input>`

### CODE REVIEW

**Comment by kyleledbetter** [comment]
should we document this anywhere or maybe create a Core/Utilities page in the /components area of docs?

**Comment by emoralesb05** [comment]
Yes, it might be a good idea to do so. We can merge this and validations and then create a PR to add docs for every directive/validator.

**Comment by kyleledbetter** [comment]
i'm about to push to this branch so we can get it started

**Comment by kyleledbetter** [comment]
image

**Pull request merged**
