### PR TITLE
fix (npm): set main config

### PR DESCRIPTION
**Pull request by playerx**
fixed module loading while using webpack, not angular cli.

### CODE REVIEW

**Comment by playerx** [comment]
hi @coveralls, should i improve something? Do u know why coverage became 67.654?

**Comment by emoralesb05** [comment]
Thanks for the heads up and contribution! 

The `coveralls` thing is an automatic message that tells you the overall code coverage. In this case you only modified the `package.json` so there is no need to add unit tests.

**Comment by playerx** [comment]
Thanks for info :)

Can you tell me the release date of next patch (0.10.3) with this pull request?

Thanks & GJ 👍

**Comment by richavyas** [comment]
Hi @playerx there would be no patch. We would do a release sometime later this month, Thanks.

**Comment by richavyas** [comment]
Would be fixed when we handle #246

**Comment by playerx** [comment]
Cool thanks 👍

**Comment by emoralesb05** [comment]
Ill close this for now, but we are planning on tackling this for beta.2.

**Pull request closed without merging**
