### PR TITLE
fix(pipes): convert bytes using powers of 2 in `TdBytesPipe`. (closes #527)

### LINKED ISSUE #527: bytes pipe doesn't convert correctly
#### Bug Report

The bytes pipe should be converting using powers of two (1024 for KB, 1,048,576 for MB, etc) not powers of 10.
` {{ 1024 | bytes }}` is returned as 1.02 KB

##### Screenshots or link to CodePen/Plunker/JSfiddle
screen shot 2017-04-27 at 3 35 19 pm
Plunker: http://plnkr.co/edit/gLMsYWq064zvaN9FOl32

#### What is the expected behavior?
pipe should divide by powers of two- {{ 1024 | bytes }} should equal 1 KB.  1 MB does not equal 1,000,000 bytes.

#### What is the motivation / use case for changing the behavior?
Conform with IEEE standards etc

#### Which version of Angular and Material, and which browser and OS does this issue affect?
All of them.
Did this work in previous versions of Angular / Material?
No.

### PR DESCRIPTION
**Pull request by aciccarello**
## Description

Modified the TdBytesPipe to convert using 1024 bytes per Kilobyte (technically [Kilibyte](https://en.wikipedia.org/wiki/Kibibyte)).

Closes #527

### What's included?

- Updated pipe conversion
- Updated unit test numbers

#### Test Steps

- [ ] npm test
- [ ] ng serve and view docs

#### General Tests for Every PR

- [ ] `ng serve --aot` still works. _(Hung at 92% chunk asset optimization on local machine)_
- [x] `npm run lint` passes.
- [x] `npm test` passes and code coverage is not lower.
- [x] `npm run build` still works.

##### Screenshots or link to CodePen/Plunker/JSfiddle
Per #527 http://plnkr.co/edit/gLMsYWq064zvaN9FOl32

### CODE REVIEW

**Comment by emoralesb05** [comment]
w000t! awesome @aciccarello !

**Comment by emoralesb05** [comment]
LGTM! Thanks dude!

**Comment by ilsiepotamus** [comment]
👍

**Comment by jeremysmartt** [comment]
👍

**Comment by stevenov7** [comment]
👍

**Pull request merged**
