### PR TITLE
fix(deprecation) switch to DOCUMENT injection token in @angular/common

### LINKED ISSUE #1390: Add Angular 8 compatibility
### Feature Request
Please make @covalent/core compatible with Angular 8

#### What is the expected behavior?
Covalent package works fine in Angular 8 project.

#### What is the motivation / use case for changing the behavior?
Angular 8 features

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular 8 

##### Other information
This error happening after angular 7.2 -> angular 8.0 migration. ("@covalent/core": "^2.0.1" is used)
image

### PR DESCRIPTION
**Pull request by dlq84**
## Description
Fixes #1390
changed import to Import `DOCUMENT` from `@angular/common` rather than the deprecated export in `platform-browser`.

### What's included?
Just three import changes

#### Test Steps

There is no changes requiring manual testing

#### General Tests for Every PR

- [X] `npm run serve:prod` still works.
- [X] `npm run tslint` passes.
- [X] `npm run stylelint` passes.
- [X] `npm test` passes and code coverage is not lower.
- [X] `npm run build:lib` still works.

##### Screenshots or link to StackBlitz/Plunker
Not needed

### CODE REVIEW

**Comment by nikolayr1** [comment]
This PR resolves this issue: https://github.com/Teradata/covalent/issues/1390

**Comment by dlq84** [comment]
Is it possible to get an estimate on when this can be merged? This is the only blocker for my team to migrate to Angular 8.

**Comment by nikolayr1** [comment]
I have the same story as @dlq84

**Comment by DaSchTour** [comment]
I just removed Covalent from my Project. No story anymore 😄

**Comment by emoralesb05** [comment]
Sorry for the delay.. work has been extra hectic these past months.

Thanks for this!

**Pull request merged**
