### PR TITLE
feat(): upgrade to material@beta.11

### PR DESCRIPTION
**Pull request by emoralesb05**
## Description

Following the breaking changes from https://github.com/angular/material2/releases/tag/2.0.0-beta.11, this will give covalent the beta.11 support (provided the mat- prefix is used)

#### Test Steps
- [ ] `yarn install`
- [ ] `ng serve`
- [ ] See all still working

#### General Tests for Every PR

- [ ] `ng serve --aot` still works.
- [ ] `npm run lint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build` still works.

### CODE REVIEW

**Comment by jerryorta-dev** [comment]
Have strange text wrapping on notifications page.
screen shot 2017-09-29 at 2 24 00 pm

**Comment by jerryorta-dev** [comment]
Syntax Highlighting component - more text issues

covalent-text-issue

**Comment by jerryorta-dev** [comment]
Text Issues on these pages:
* http://localhost:4200/#/components/code-editor
* http://localhost:4200/#/components/text-editor



screen shot 2017-09-29 at 2 32 59 pm

**Comment by aciccarello** [comment]
@jerryorta-dev I think those may be existing issues unrelated to this PR. The existing docs site has the text-wrapping problem on the notifications page.
image

**Comment by kyleledbetter** [comment]
This was probably introduced last release since table rows now have height

**Comment by jbojcic1** [comment]
When could we roughly expect this to be in?

**Comment by emoralesb05** [comment]
@jerryorta-dev yeah, this was introduced with the data table changes.. this will probably need to be reworked and show a list instead of a table since the description is to big for a table.. (feature for td-pretty-markdown)

**Comment by emoralesb05** [comment]
@jbojcic1 hopefully in the next few days, this requires lots of testing to be sure we dont break anything

**Comment by jeremysmartt** [comment]
Text in the API Summary on Notifications looks strange:

screen shot 2017-10-02 at 1 16 53 pm

**Comment by jeremysmartt** [comment]
When toggling to the Code Tab and then back to Demo tab the Expansion Panels no longer work

expansion bug

**Comment by jeremysmartt** [comment]
Adding a file to the File Input clobbers the text on the input box:

screen shot 2017-10-02 at 1 30 00 pm

**Comment by jeremysmartt** [comment]
Typo: "Reponsiveness"

screen shot 2017-10-02 at 2 06 32 pm

**Comment by jeremysmartt** [comment]
Selecting a chip doesn't work in IE11:

screen shot 2017-10-02 at 2 50 55 pm

**Comment by jeremysmartt** [comment]
Chips Events demo acts weird in IE11:

chips event demo

**Comment by jeremysmartt** [comment]
Description Resize doesn't work in IE11:

description resize

**Comment by jeremysmartt** [comment]
Using Selection on Rows in Table creates strange concatenated Title in Message area:

selection title

**Comment by jeremysmartt** [comment]
Tooltips on column headers in IE11 don't work:

tooltips

**Comment by jeremysmartt** [comment]
Clear button on Search doesn't work in IE11:

clear

**Comment by jeremysmartt** [comment]
Extra Padding at end of Virtual Scroll in IE11:

screen shot 2017-10-02 at 3 34 44 pm

**Comment by jeremysmartt** [comment]
Looks like some kind of change detection issue with the Collapse Animation in IE11:

collapse animation

**Comment by emoralesb05** [comment]
Created issues for the findings, merging this since most of them are unrelated to the upgrade.

**Pull request merged**
