### PR TITLE
feat: add info and help guide

### PR DESCRIPTION
**Pull request by ecni19**
## Description

Added the info and help guide from [Figma](https://www.figma.com/file/CQlXKYDbZ34DeSUqS7LoVv/Guide---Info-%26-help?node-id=137%3A275). 

### What's included?

- New info and help story added under "Guides". 
  - `covalent-sigma/stories/info-and-help.stories.mdx` was added. 

#### Test Steps

- [ ] `npm run storybook`
- [ ] Navigate to "Info and help" under "Guides"
- [ ] Compare the story with this [Figma](https://www.figma.com/file/CQlXKYDbZ34DeSUqS7LoVv/Guide---Info-%26-help?node-id=137%3A275).   

#### General Tests for Every PR

- [x] `npm run start` still works.
- [x] `npm run lint` passes.
- [ ] `npm run stylelint` passes.
- [x] `npm test` passes and code coverage is not lower.
- [x] `npm run build` still works.

### CODE REVIEW

**Comment by owilliams320** [comment]
@ecni19 can you add a gif or screenshot?

**Comment by ecni19** [comment]
> @ecni19 can you add a gif or screenshot?

ItemDetailAndEditing

**Comment by owilliams320** [comment]
@ecni19 this looks like item detail & editing? is that the right name for this file or is the GIF different

**Comment by ecni19** [comment]
> @ecni19 this looks like item detail & editing? is that the right name for this file or is the GIF different

Ah so sorry, I attached the wrong gif. Here's the correct one

InfoAndHelp

**Pull request merged**
