### PR TITLE
Feat/angular 11

### PR DESCRIPTION
**Pull request by vhdirk**
## Description
Upgrade to Angular 11

### What's included?
* Updated Angular core and material to version 11

#### Test Steps
- [x] Avoid error trying to update webdriver by setting the following in your environment: 
  `export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD='true'`
- [x] `npm run serve`
  Verify demos still work as expected
- [x] `npm run serve:prod`
  Verify demos still work as expected
- [x] `npm run build:lib`
  Verify builds to completion

#### General Tests for Every PR

- [x] `npm run serve:prod` still works.
- [x] `npm run tslint` passes.
- [x] `npm run stylelint` passes.
- [x] `npm test` passes and code coverage is not lower.
- [x] `npm run build:lib` still works.

### CODE REVIEW

**Comment by Zwartpet** [comment]
@jeremysmartt Hi, is the covalent project less supported nowadays? Not so long ago features like this would not stay pending for weeks.

**Comment by ho0** [comment]
@vhdirk I get 4 failed test when I run ng test.

**Comment by vhdirk** [comment]
@ho0 That's odd. I ran `npm run test` (and kept the browser focused). CI also seems to confirm that all tests pass?

**Comment by ho0** [comment]
@vhdirk I ran it 4 times. It passed 3 times and I was almost ready say your right, and then on the 4th time I got 22 errors. So I think we have some kind of unit test dependency issue with the tests. If you run it multiple times do you eventuall get errors?

**Comment by vhdirk** [comment]
@ho0 I've let it run several times now. It's only when I get impatient and forget that this browser window needs constant focus that these tests go sideways. 
I've had a good experience with Jest instead of Jasmine, but seeing how long this PR is open, I'm not expecting substantial changes there either.

**Comment by vhdirk** [comment]
@emoralesb05 @JulieMarie When could we expect a release (beta) that includes this PR? This is currently blocking us from moving to angular 11 for our application.
Thanks for you time and effort!

**Comment by JulieMarie** [comment]
Let me see what I can do @vhdirk to get this done as soon as possible!

**Pull request merged**
