### PR TITLE
feat(dependencies): upgrade to @angular@4.2.0

### PR DESCRIPTION
**Pull request by emoralesb05**
## Description

https://github.com/angular/angular/blob/master/CHANGELOG.md#420-salubrious-stratagem-2017-06-08

Now that angular really exposes the programmatic animations API. We can start leveraging them for `tdToggle` and `tdFade` instead of depending on the experimental API.

this will grant better support and not depend on `BrowserAnimationsModule` (now we can use `NoopAnimationsModule`)

### What's included?

- feat(toggle): make toggle directive use new animations API
- feat(fade): make fade directive use new animations API
- fix(media): make media service not use `window` directly 
- chore(): bump module dependencies to `@angular@4.2.0`
- chore(): bump to `@angular/cli@1.1.1`

#### Test Steps

- [x] `npm run reinstall`
- [x] Play with `directives` demo and `media` demo
- [x] Also check all components to see that they still work fine

#### General Tests for Every PR

- [x] `ng serve --aot` still works.
- [x] `npm run lint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [ ] `npm run build` still works.

##### Screenshots or link to CodePen/Plunker/JSfiddle

### CODE REVIEW

**Comment by emoralesb05** [comment]
Everything seems good to go in 4.2.0-rc.1, so we can merge this as soon as they release stable.

**Comment by emoralesb05** [comment]
All good in 4.2.0-rc.2 and angular/cli@1.1.0

**Comment by emoralesb05** [comment]
Now we need to test everything in 4.2.0 stable.

Already fixed a few issues i found (and there is an issue in the ngx-charts demo.

Need more eyes on this PR

**Comment by JoshSchoen** [comment]
@emoralesb05 for ngx-charts package.json is using 5.0.0. Updating to the latest, 5.3.1 looks to fix the issue.

**Comment by emoralesb05** [comment]
Awesome, just tested it and it worked! Thanks! 😄

**Comment by JoshSchoen** [comment]
I haven't come across anything else yet but I'll keep testing.

**Comment by ilsiepotamus** [comment]
LGTM!

**Comment by jerryorta-dev** [comment]
Should the "Updates" say something about supporting Angular 4.2.0? I know the changelog is linked, so just wondering if this fact is elevated to the dropdown.

**Comment by jerryorta-dev** [comment]
Content scrolled is not resetting to top when navigating to another view:

**Whan** navigating to [http://localhost:4200/#/components/steps](http://localhost:4200/#/components/steps) 
**And** scrolling content all the way down 
**And** navigating to another component using the side menu 
**Then** the new content is NOT starting from the top, it's scroll to the same position as the previous content viewed.

**Comment by emoralesb05** [comment]
Good catch, thats been there for a while now and has always bugged me. Can you open an issue so we can tackle it in a separate PR?

**Comment by jerryorta-dev** [comment]
> Good catch, thats been there for a while now and has always bugged me. Can you open an issue so we can tackle it in a separate PR?

@emoralesb05 will open and issue

**Comment by stevenov7** [comment]
LGTM

**Pull request merged**
