### PR TITLE
ECharts: support tree shaking

### PR DESCRIPTION
**Pull request by vhdirk**
## Description

As mentioned in https://github.com/Teradata/covalent/issues/1933, the user currently has make the echarts library globally available. This PR provides a way to resolve that and enable full tree-shaking support. This should also be a partial fix for https://github.com/Teradata/covalent/issues/1775.

### What's included?
This PR introduces a new `TD_ECHARTS_CONFIG` injectiontoken that is used to pass the `echarts` library reference to `CovalentBaseEchartsModule`. 

```
import * as echartsLibraryReference from 'echarts';

...
  CovalentBaseEchartsModule.forRoot({
    echarts: echartsLibraryReference,
    defaultThemes: false
  }),

or  

providers: [{
  provide: TD_ECHARTS_CONFIG,
  useValue: {
    echarts: echartsLibraryReference,
    defaultThemes: false
  }
}]

```

#### Test Steps

- [ ] `npm run start`
- [ ] then this
- [ ] finally this

#### General Tests for Every PR

- [x] `npm run start` still works.
- [x] `npm run lint` passes.
- [ ] `npm run stylelint` passes.
- [ ] `npm test` passes and code coverage is not lower.
- [x] `npm run build` still works.

### CODE REVIEW

**Review by owilliams320 — CHANGES_REQUESTED** [review]
@vhdirk  Can you seperate out the schematic and a11y additions if that is not related to echarts?

**Comment by owilliams320** [comment]
@vhdirk looks like the tests and e2e job is failing can you fix this?

**Comment by vhdirk** [comment]
@owilliams320 unfortunately, I'm having some time of for personal reasons. I won't be able to work on this for a while.

**Comment by vhdirk** [comment]
@owilliams320 unfortunately, I'm having some time of for personal reasons. I won't be able to work on this for a while.

**Pull request closed without merging**
