### PR TITLE
feature(material): Upgrade to latest material. (closes #346)

### LINKED ISSUE #346: TdAutoCompleteComponent incompatibility with Angular Material Beta 2
Angular has updated Material lib to 2.0.0-beta.2. Now it includes its own autocomplete control, This cause Covalent exception during compilation.
To repro:
just update your Material to beta.2 and run the project. I got this result on completely empty project I generated using Angular CLI. Rolling back to 2.0.0-beta.1 solves the issue.
Angular ver: 2.4.7
Angular CLI ver: 1.0.0-beta.32.3
Angular compiler CLI ver: 2.4.7
Material ver: 2.0.0-beta.2
Covalent Core ver: 1.0.0-beta.1-1
Here is console output:
```
Unhandled Promise rejection: Template parse errors:
Can't bind to 'placeholder' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'placeholder' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
  <md-input flex="100" 
            [(ngModel)]="value"
            [ERROR ->][placeholder]="placeholder"
            [autofocus]="autoFocus"
            [list]="listName"
"): TdAutoCompleteComponent@3:12
Can't bind to 'autofocus' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'autofocus' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
            [(ngModel)]="value"
            [placeholder]="placeholder"
            [ERROR ->][autofocus]="autoFocus"
            [list]="listName"
            [max]="max"
"): TdAutoCompleteComponent@4:12
Can't bind to 'list' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'list' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
            [placeholder]="placeholder"
            [autofocus]="autoFocus"
            [ERROR ->][list]="listName"
            [max]="max"
            [maxlength]="maxLength"
"): TdAutoCompleteComponent@5:12
Can't bind to 'max' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'max' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
            [autofocus]="autoFocus"
            [list]="listName"
            [ERROR ->][max]="max"
            [maxlength]="maxLength"
            [min]="min"
"): TdAutoCompleteComponent@6:12
Can't bind to 'min' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'min' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
            [max]="max"
            [maxlength]="maxLength"
            [ERROR ->][min]="min"
            [minlength]="minLength"
            [readonly]="readOnly"
"): TdAutoCompleteComponent@8:12
Can't bind to 'readOnly' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'readOnly' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
            [min]="min"
            [minlength]="minLength"
            [ERROR ->][readonly]="readOnly"
            [disabled]="disabled"
            [required]="required"
"): TdAutoCompleteComponent@10:12
'md-input' is not a known element:
1. If 'md-input' is an Angular component, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("<div flex>
  [ERROR ->]<md-input flex="100" 
            [(ngModel)]="value"
            [placeholder]="placeholder"
"): TdAutoCompleteComponent@1:2 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError {__zone_symbol__error: Error: Template parse errors:
Can't bind to 'placeholder' since it isn't a known property of 'md-inp…, _nativeError: ZoneAwareError, __zone_symbol__stack: "Error: Template parse errors:↵Can't bind to 'place…ttp://localhost:4200/polyfills.bundle.js:3125:35)", __zone_symbol__message: "Template parse errors:↵Can't bind to 'placeholder'…er]="placeholder"↵"): TdAutoCompleteComponent@1:2"} Error: Template parse errors:
Can't bind to 'placeholder' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'placeholder' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
  <md-input flex="100" 
            [(ngModel)]="value"
            [ERROR ->][placeholder]="placeholder"
            [autofocus]="autoFocus"
            [list]="listName"
"): TdAutoCompleteComponent@3:12
Can't bind to 'autofocus' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'autofocus' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
            [(ngModel)]="value"
            [placeholder]="placeholder"
            [ERROR ->][autofocus]="autoFocus"
            [list]="listName"
            [max]="max"
"): TdAutoCompleteComponent@4:12
Can't bind to 'list' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'list' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
            [placeholder]="placeholder"
            [autofocus]="autoFocus"
            [ERROR ->][list]="listName"
            [max]="max"
            [maxlength]="maxLength"
"): TdAutoCompleteComponent@5:12
Can't bind to 'max' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'max' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
            [autofocus]="autoFocus"
            [list]="listName"
            [ERROR ->][max]="max"
            [maxlength]="maxLength"
            [min]="min"
"): TdAutoCompleteComponent@6:12
Can't bind to 'min' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'min' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
            [max]="max"
            [maxlength]="maxLength"
            [ERROR ->][min]="min"
            [minlength]="minLength"
            [readonly]="readOnly"
"): TdAutoCompleteComponent@8:12
Can't bind to 'readOnly' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'readOnly' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
            [min]="min"
            [minlength]="minLength"
            [ERROR ->][readonly]="readOnly"
            [disabled]="disabled"
            [required]="required"
"): TdAutoCompleteComponent@10:12
'md-input' is not a known element:
1. If 'md-input' is an Angular component, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("<div flex>
  [ERROR ->]<md-input flex="100" 
            [(ngModel)]="value"
            [placeholder]="placeholder"
"): TdAutoCompleteComponent@1:2
    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3554:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:87366:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6598:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:21040:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:59251:68)
    at http://localhost:4200/vendor.bundle.js:59134:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:59134:19)
    at createResult (http://localhost:4200/vendor.bundle.js:59016:19)
    at ZoneDelegate.webpackJsonp.925.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2926:26)
    at Zone.webpackJsonp.925.Zone.run (http://localhost:4200/polyfills.bundle.js:2722:43)
    at http://localhost:4200/polyfills.bundle.js:3275:57
    at ZoneDelegate.webpackJsonp.925.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:2959:31)
    at Zone.webpackJsonp.925.Zone.runTask (http://localhost:4200/polyfills.bundle.js:2762:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:3125:35)
consoleError @ zone.js:516
_loop_1 @ zone.js:545
drainMicroTaskQueue @ zone.js:549
```

### PR DESCRIPTION
**Pull request by emoralesb05**
## Description

Upgrade to latest `@angular/material@2.0.0-beta.2`. https://github.com/angular/material2/blob/master/CHANGELOG.md#200-beta2-flannel-papaya-2017-02-15

### What's included?

Material Changes:
- Breaking change from `material` where `md-input` has been removed as component and directive in favor of the `mdInput` directive selector.
- Leverage new input of `md-menu` `[overlapTrigger]="false"` in notifications demo so the menu doesnt overlap the `icon`
- Now we can use the `(change)` event from `md-select`.

Covalent Changes/Fixes because of `material`:
- **internal(efficiency):** No more need for `refresh` work around for `tooltips` used under `OnPush` https://github.com/angular/material2/commit/632b964b0dd1cf15349265ec118a6844e6cec9d0
- **bugfix(layout):** Leverage `disableClose` input from sidenav to prevent `ESC` closing the sidenav on `side` mode. https://github.com/angular/material2/commit/52ade97cfc91d22b9d5b0c77c7bd09581816f5a0
- **bugfix(dynamic-forms):** `number` type input works again.
- **feature(data-table):** Leverage the `md-pseudo-checkbox` to render the selectable rows more efficiently. https://github.com/angular/material2/commit/3b6cab01c7ff44c999ffcdc99d2ec9a2fb63e96a

#### Test Steps

- `npm run reinstall`
- `ng serve`
- Play around with docs

#### General Tests for Every PR

- [x] `ng serve --aot` still works.
- [x] `npm run lint` passes.
- [x] `npm test` passes and code coverage is not lower.
- [x] `npm run build` still works.

NOTE: Needs heavy testing on all fronts since the `.mat` prefix change affected how certain rules are applied.

### CODE REVIEW

**Comment by d3viant0ne** [comment]
@emoralesb05 - Don't know if you have been watching master but you may want to wait for the compatibility mode changes to stabilize a bit so you don't end up doing this again in a few weeks :)

**Comment by emoralesb05** [comment]
@d3viant0ne Yeah haha i've been watching master almost daily, and we were trying to get ahead so we could release asap (after they released `beta.2`).. but its gonna be hard to do so with this particular set of changes.

**Comment by d3viant0ne** [comment]
Yay! beta.2 :)

**Comment by emoralesb05** [comment]
@d3viant0ne 😄  finally! We still have a few styling errors with icons, but we have covered almost everything. 

I am gonna keep testing stuff over the next few days and hopefully we can merge this soon and release our `beta.2` 💥

**Comment by d3viant0ne** [comment]
Yeah, this one has been a long time coming. Playing with your branch now, looks like it's pretty close :)

**Comment by thekalinga** [comment]
@d3viant0ne Why button variations are not named using camel case?

`md-input` is renamed to `mdInput`, but not `md-button` to `mdButton`. Any idea why?

**Comment by d3viant0ne** [comment]
@thekalinga - as far as I know, this is very much a work in progress. Last I looked @emoralesb05 was working on inputs & issues with the icons.

There is still more work required before this PR is ready to be landed thus the `don't merge` label.

**Comment by thekalinga** [comment]
@d3viant0ne I have just looked at material repo. They too seems to be using `md-button` for button but `mdInput` for input. I could not figure out why :)

**Comment by emoralesb05** [comment]
quite from the `material` changelog a while back:

`all @Directive selectors are now camelCase to be consistent with Angular core. For example, [md-tooltip] is now [mdTooltip]`

This means `md-button` will stay the way it is because its a component targeting `button[md-button]`. While `mdInput` is a directive.

**Comment by thekalinga** [comment]
@emoralesb05 Thanks for that. I get it now.

But what I don't get is why a component is made to resemble an html attribute (which would make me feel that its an directive).

I'm not sure if the same thing can be achieved with just declaring `md-button` to be attribute directive, so that everything will remain consistent.

Just for ref: https://github.com/angular/material2/blob/140c95c2e891c1fb5cc6bb49e08a95ada2c0406c/src/lib/button/button.ts#L82-L100

**Comment by emoralesb05** [comment]
The reason is even though you feel its an "attribute", its a `component` selector that leverages the `button` targeted with it as a host element and creates a body for it. 

It does **not** create a new `button` element.

**Comment by d3viant0ne** [comment]
They really did thoroughly break the ripple speed attribute. The ripple on `md-tab` is like watching grass grow. Honestly, it's kind of amusing.

**Comment by thekalinga** [comment]
Agree with your explanation on why it is behaving the way it is behaving.

Syntactically, `md-button` have its own `template` associated. so we would obviously annotate it as such.

But my question was more along the lines, cant the directive modify the host (`button` in this case to which `mdButton` can add additional DOM elements) and be declared as a directive.

This way, our mental model would be much simpler.

i.e element => component, attribute => directive.

**Comment by emoralesb05** [comment]
A directive has many limitations and you wouldnt be able to achieve what you want with it. A directive is only meant to add or modify behavior, you cant really have a body nor leverage shadowdom.

And `<md-button>` as component would need to create its own underlying `button` and then expose all the inputs which is a lot of boilerplate code to achieve something that can be done by `button[md-button]`.

If you have more questions, i advice you to ask in the `material` repo.

**Comment by thekalinga** [comment]
@emoralesb05 Thanks :)

**Comment by thekalinga** [comment]
Just created an [issue ](https://github.com/angular/material2/issues/3125)in material2.

**Comment by asaph26** [comment]
@emoralesb05: Would this be merged with master and available as part of the nightlies before the weekend?

**Comment by emoralesb05** [comment]
Not really because we still have issues with styling and requires heavy testing. We are trying our best to release this following week, once we merge this PR in particular.

**Comment by d3viant0ne** [comment]
@emoralesb05 - Speaking of testing, this in a place where some testing would be of value or still too WIP currently?

If yes, do you want issues listed out here or a pull request into this branch fixing said issues?

**Comment by emoralesb05** [comment]
@d3viant0ne im currently waiting for @kyleledbetter to jump in and do his magic from a `scss` utility perspective (since there are still issues with some rules not overriding other ones), but if you find other things please let us know 😄.

A PR against this one would be awesome.

**Pull request merged**
