### PR TITLE
fix(code-editor): dispose the event listener when the component is destroyed

### PR DESCRIPTION
**Pull request by arturovt**
#### General Tests for Every PR

- [x] `npm run serve:prod` still works.
- [x] `npm run tslint` passes.
- [x] `npm run stylelint` passes.
- [x] `npm test` passes and code coverage is not lower.
- [x] `npm run build:lib` still works.

### CODE REVIEW

**Comment by owilliams320** [comment]
Thanks for the contribution @arturovt 🥳  Currently the develop branch is under development for 4.x and is in alpha phase. Is that your intended version?

**Comment by arturovt** [comment]
Hey @owilliams320. Should I switch the branch to something else? Btw what means "intended version"?

**Review by owilliams320 — APPROVED** [review]
LGTM

**Pull request merged**
